# Generated by Django 5.2.5 on 2025-08-22 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_product_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='products',
        ),
    ]
