# Generated by Django 5.2.5 on 2025-08-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_customer_customers_rename_order_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='note',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
